
import type { Car, User, Booking } from '@/types';

export const mockCars: Car[] = [
  {
    id: '1',
    name: 'Toyota Camry',
    type: 'Sedan',
    pricePerHour: 50, // Changed from pricePerDay
    minNegotiablePrice: 45,
    maxNegotiablePrice: 55,
    imageUrls: ['/assets/images/mock-camry-front.png', '/assets/images/mock-camry-side.png'],
    aiHint: 'sedan silver',
    description: 'Reliable and fuel-efficient sedan.',
    longDescription: 'The Toyota Camry is a benchmark for midsize sedans, offering a comfortable ride, spacious interior, and excellent fuel economy. Perfect for city driving and long road trips, it comes equipped with modern safety features and a user-friendly infotainment system.',
    features: ['Air Conditioning', 'GPS Navigation', 'Bluetooth', 'Automatic Transmission'],
    availability: [{ startDate: '2024-08-01', endDate: '2024-12-31'}],
    seats: 5,
    engine: '2.5L 4-Cylinder',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    rating: 4.5,
    reviews: 120,
    location: 'Downtown Central',
  },
  {
    id: '2',
    name: 'Honda CR-V',
    type: 'SUV',
    pricePerHour: 70, // Changed from pricePerDay
    minNegotiablePrice: 65,
    maxNegotiablePrice: 75,
    imageUrls: ['/assets/images/mock-crv-view.png'],
    aiHint: 'suv blue',
    description: 'Spacious and versatile SUV for families.',
    longDescription: 'The Honda CR-V is a compact SUV known for its practicality, reliability, and spacious cargo hold. It offers a smooth ride, comfortable seating for five, and a host of standard safety features, making it an ideal choice for families and adventurers alike.',
    features: ['Air Conditioning', 'Backup Camera', 'Apple CarPlay', 'All-Wheel Drive'],
    availability: [{ startDate: '2024-08-01', endDate: '2024-12-31'}],
    seats: 5,
    engine: '1.5L Turbocharged 4-Cylinder',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    rating: 4.7,
    reviews: 95,
    location: 'Airport Rentals',
  },
  {
    id: '3',
    name: 'Ford Mustang',
    type: 'Coupe',
    pricePerHour: 120, // Changed from pricePerDay
    // No negotiable prices set for this one, to test undefined case
    imageUrls: ['/assets/images/mock-mustang-fast.png'],
    aiHint: 'muscle car red',
    description: 'Iconic American muscle car for a thrilling ride.',
    longDescription: 'Experience the thrill of the open road with the Ford Mustang. This iconic American muscle car boasts powerful engine options, aggressive styling, and a sporty interior. Whether you choose the EcoBoost or the V8, you\'re guaranteed an exhilarating driving experience.',
    features: ['Premium Sound System', 'Leather Seats', 'Performance Tires', 'Rear-Wheel Drive'],
    availability: [{ startDate: '2024-08-15', endDate: '2024-11-30'}],
    seats: 4,
    engine: '5.0L V8',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    rating: 4.8,
    reviews: 75,
    location: 'Luxury Motors',
  },
  {
    id: '4',
    name: 'Volkswagen Golf',
    type: 'Hatchback',
    pricePerHour: 45, // Changed from pricePerDay
    minNegotiablePrice: 40,
    maxNegotiablePrice: 48,
    imageUrls: ['/assets/images/mock-golf-city.png'],
    aiHint: 'hatchback gray',
    description: 'Compact and agile, perfect for city driving.',
    longDescription: 'The Volkswagen Golf is a versatile hatchback that excels in urban environments. It offers a refined driving experience, a high-quality interior, and impressive fuel efficiency. With its compact size and nimble handling, parking and navigating city streets is a breeze.',
    features: ['Sunroof', 'Heated Seats', 'Android Auto', 'Parking Sensors'],
    availability: [{ startDate: '2024-09-01', endDate: '2024-12-31'}],
    seats: 5,
    engine: '1.4L Turbocharged 4-Cylinder',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    rating: 4.3,
    reviews: 110,
    location: 'City Center Branch',
  },
   {
    id: '5',
    name: 'Tesla Model 3',
    type: 'Sedan',
    pricePerHour: 90, // Changed from pricePerDay
    minNegotiablePrice: 85,
    maxNegotiablePrice: 90, // Max is same as initial price
    imageUrls: ['/assets/images/mock-tesla-future.png'],
    aiHint: 'electric car white',
    description: 'Cutting-edge electric vehicle with Autopilot.',
    longDescription: 'The Tesla Model 3 offers a compelling blend of performance, range, and technology. Its minimalist interior, large touchscreen display, and available Autopilot features redefine the driving experience. Enjoy instant torque and zero tailpipe emissions with this innovative EV.',
    features: ['Autopilot', 'Panoramic Glass Roof', 'Premium Audio', 'Keyless Entry'],
    availability: [{ startDate: '2024-08-01', endDate: '2024-12-31'}],
    seats: 5,
    engine: 'Electric Motor',
    transmission: 'Automatic',
    fuelType: 'Electric',
    rating: 4.9,
    reviews: 250,
    location: 'Tech Park Rentals',
  },
  {
    id: '6',
    name: 'Jeep Wrangler',
    type: 'SUV',
    pricePerHour: 85, // Changed from pricePerDay
    minNegotiablePrice: 80,
    // Max not set, should default to pricePerHour in chatbot logic
    imageUrls: ['/assets/images/mock-jeep-adventure.png'],
    aiHint: 'offroad vehicle green',
    description: 'Legendary off-road capability.',
    longDescription: 'The Jeep Wrangler is the ultimate adventure vehicle, renowned for its unparalleled off-road prowess. With removable doors and roof, rugged construction, and advanced 4x4 systems, it\'s ready to tackle any terrain you throw at it. Perfect for exploring the great outdoors.',
    features: ['4x4 Drivetrain', 'Convertible Top', 'Tow Package', 'Skid Plates'],
    availability: [{ startDate: '2024-08-10', endDate: '2024-12-20'}],
    seats: 4,
    engine: '3.6L V6',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    rating: 4.6,
    reviews: 150,
    location: 'Adventure Rentals Co.',
  },
];

export const mockUsers: User[] = [
  { id: 'u1', name: 'Alice Wonderland', email: 'alice@example.com', role: 'Admin', createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'u2', name: 'Bob The Builder', email: 'bob@example.com', role: 'User', createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'u3', name: 'Charlie Brown', email: 'charlie@example.com', role: 'User', createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString() },
];

export const mockBookings: Booking[] = [
  { 
    id: 'b1', 
    carId: '1', 
    carName: 'Toyota Camry', 
    carImageUrl: '/assets/images/mock-camry-front.png',
    userId: 'u2', 
    userName: 'Bob The Builder', 
    startDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(), 
    endDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(), 
    totalPrice: 150, 
    status: 'Completed' 
  },
  { 
    id: 'b2', 
    carId: '2', 
    carName: 'Honda CR-V', 
    carImageUrl: '/assets/images/mock-crv-view.png',
    userId: 'u3', 
    userName: 'Charlie Brown',
    startDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(), 
    endDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(), 
    totalPrice: 210, 
    status: 'Confirmed' 
  },
   { 
    id: 'b3', 
    carId: '3', 
    carName: 'Ford Mustang', 
    carImageUrl: '/assets/images/mock-mustang-fast.png',
    userId: 'u1', 
    userName: 'Alice Wonderland',
    startDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(), 
    endDate: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(), 
    totalPrice: 240, 
    status: 'Pending' 
  },
];
